version: '3.3'
services:
    db-backup:
        image: schickling/mysql-backup-s3
        restart: always
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: .mysql_password
            S3_ACCESS_KEY_ID: .s3_access_key
            S3_SECRET_ACCESS_KEY: .s3_secret_key
            S3_BUCKET: .bucket
            S3_PREFIX: ''
            SCHEDULE: "@daily"
    db:
        image: 'mysql:5.6'
        restart: always
        volumes:
            - './mysql:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: .mysql_password
    php:
        image: 'mautic/mautic:fpm'
        restart: always
        depends_on:
            - db
        volumes:
            - './mautic:/var/www/html'
        environment:
            MAUTIC_DB_HOST: db
            MAUTIC_DB_USER: root
            MAUTIC_DB_PASSWORD: .mysql_password
            MAUTIC_DB_NAME: mautic
            MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    web:
        image: nginx
        depends_on:
            - php
        restart: always
        volumes:
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
            - './mautic:/var/www/html'
            - './logs:/var/log/nginx'
    https-portal:
        image: 'steveltn/https-portal:1'
        depends_on:
            - web
        ports:
            - '80:80'
            - '443:443'
        restart: always
        volumes:
            - './ssl_certs:/var/lib/https-portal'
        environment:
            DOMAINS: '.domain -> http://web:80 #production'
            CLIENT_MAX_BODY_SIZE: 64M
